### ISSUE TITLE
Workspace Cards Dashboard

### ISSUE THREAD

**Issue by waveywaves** [che-electron/client#3]
This would contain the Cards required to access individual workspaces which the user would be authorized to use.

- [x] Make Parent Component in React #10 
- [x] Make Workspace Card Component #10  
- [x] Add functionality to Workspace Card Component start, stop and access Workspaces #11 
- [x] Workspace Card reflects the Current Status of the Workspace and Workspace Type #10
